# Copyright 2026 Google LLC
# Licensed under the Apache License, Version 2.0
"""Cross-Cutting Observability & Telemetry Plugin.

This module provides standard, non-invasive telemetry tracing across the entire
triage workflow. By leveraging the ADK plugin lifecycle hooks (before/after agent,
model, and tool callbacks), we achieve:
1. Step-by-step agent tracking (e.g. logging when an agent node starts/stops).
2. End-to-end execution latency measurement (using monotonic timers).
3. Real-time token consumption accounting (cumulative input and output tokens).
4. Detailed tool execution audits (tracking tool parameters and return statuses).

This design allows developers to track and audit the entire system's behavior without
scattering logging boilerplate across individual agents or routing engines.
"""

from __future__ import annotations

import logging
import time
from typing import Any

from google.adk.agents import BaseAgent
from google.adk.agents.callback_context import CallbackContext
from google.adk.agents.invocation_context import InvocationContext
from google.adk.models.llm_response import LlmResponse
from google.adk.plugins.base_plugin import BasePlugin
from google.adk.tools import BaseTool
from google.adk.tools.tool_context import ToolContext
from google.genai import types

logger = logging.getLogger("smart_care_triage")


class ObservabilityPlugin(BasePlugin):
    """Timing, token accounting, and step/tool tracing middleware."""

    def __init__(self) -> None:
        super().__init__(name="observability")

    # =====================================================================
    # Run Callbacks (end-to-end latency anchor)
    # =====================================================================
    # The ADK 2.x Workflow root is not a BaseAgent, so agent callbacks never
    # fire for it — the run-level hooks are the reliable anchor. On a paused
    # (HITL) run the timer restarts on resume, so latency measures the active
    # segment, not reviewer wait time.

    async def before_run_callback(
        self, *, invocation_context: InvocationContext
    ) -> types.Content | None:
        state = invocation_context.session.state
        state["temp:t0"] = time.monotonic()
        state.setdefault("total_tokens", 0)
        return None

    async def after_run_callback(
        self, *, invocation_context: InvocationContext
    ) -> None:
        state = invocation_context.session.state
        t0 = state.get("temp:t0")
        if t0 is not None:
            state["latency_ms"] = round((time.monotonic() - t0) * 1000)
        logger.info(
            "[done] latency=%sms tokens=%s",
            state.get("latency_ms"),
            state.get("total_tokens"),
        )
        return None

    # =====================================================================
    # Agent Step Callbacks (Workflow and Sub-node execution tracing)
    # =====================================================================

    async def before_agent_callback(
        self, *, agent: BaseAgent, callback_context: CallbackContext
    ) -> types.Content | None:
        """Lifecycle hook triggered right before any agent node is executed."""
        logger.info("[step] -> %s", agent.name)
        return None

    # =====================================================================
    # Model Callbacks (Real-time LLM Token Consumption Accounting)
    # =====================================================================

    async def after_model_callback(
        self, *, callback_context: CallbackContext, llm_response: LlmResponse
    ) -> LlmResponse | None:
        """Lifecycle hook triggered whenever any Gemini API call receives a response."""
        # Read the raw metadata generated by Gemini and accumulate total token count
        usage = getattr(llm_response, "usage_metadata", None)
        total = getattr(usage, "total_token_count", None) if usage else None
        if total:
            callback_context.state["total_tokens"] = (
                callback_context.state.get("total_tokens", 0) + total
            )
        return None

    # =====================================================================
    # Tool Callbacks (Function and MCP execution logging)
    # =====================================================================

    async def before_tool_callback(
        self, *, tool: BaseTool, tool_args: dict[str, Any], tool_context: ToolContext
    ) -> dict | None:
        """Lifecycle hook triggered right before any Tool is executed (e.g. MCP guidelines)."""
        logger.info("[tool ->] %s(%s)", tool.name, tool_args)
        return None

    async def after_tool_callback(
        self,
        *,
        tool: BaseTool,
        tool_args: dict[str, Any],
        tool_context: ToolContext,
        result: dict,
    ) -> dict | None:
        """Lifecycle hook triggered right after a Tool completes execution."""
        status = result.get("status") if isinstance(result, dict) else "?"
        logger.info("[tool <-] %s: %s", tool.name, status)
        return None
